### ISSUE TITLE
How do I start the bot

### ISSUE THREAD

**Issue by Exosylver** [tulir/tgfilestream#11]
Please make instructions, or tell me and I'll contribute them. It doesn't say anywhere where I should put in the api id's and so on.

**Comment by pseudokawaii** [comment]
@Exosylver If you are deploying on Heroku, then use their vars feature from app settings to set the environment variables. But if you're using any platform which doesn't support external vars feature than make a file name `.env` to store all the environment variables.

You don't need to do anything to start the bot if you're using Heroku, just restart the worker after you've set the environment variables. But if you're using a terminal to control the bot, execute `python3 -m tgfilestream` to start the bot.
