### ISSUE TITLE
Download does not start

### ISSUE THREAD

**Issue by GianlucaTarantino** [tulir/tgfilestream#22]
The download from the provided link does not start. I've set everything correctly (I think, I've set HOST to 0.0.0.0 and PUBLIC_URL to http://serverip:8080), the bot provides a link (in stdout because I needed the link there), the link seem to work correctly because I can see the file name and the weight, but the download is stuck at 0%

**Comment by xcoders-hub** [comment]
Facing same issue. Did you fixed that ?

**Comment by Daniel3k00** [comment]
i have this problem too. does anyone know how to fix this problem?

**Comment by D4n13l3k00** [comment]
I solve this problem

Just install telethon 1.15.0

pip3 install telethon==1.15.0
